### ISSUE TITLE
Readthedocs failing with sphinxawesome-theme

### ISSUE THREAD

**Issue by onyeibo** [kai687/sphinxawesome-theme#1964]
It was not finding the theme so I followed the recommendations on this page https://sphinxawesome.xyz/how-to/add/#load-the-theme-from-a-local-directory

Now getting:
```
Extension error:
Could not import extension sphinxawesome_theme (exception: No module named 'bs4')
```

Build works locally (I have bs4 on local virtual environment.  How do I ensure that readthedocs replicates the local build?

**Comment by onyeibo** [comment]
> Did you receive an error message? I use this theme on ReadTheDocs just fine.

Running Sphinx v8.0.2
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sitewide-development/envs/latest/lib/python3.12/site-packages/sphinx/registry.py", line 448, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.12.3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/sitewide-development/checkouts/latest/sitewide/docs/_themes/sphinxawesome_theme/__init__.py", line 25, in <module>
    from .postprocess import changed_docs, post_process_html
  File "/home/docs/checkouts/readthedocs.org/user_builds/sitewide-development/checkouts/latest/sitewide/docs/_themes/sphinxawesome_theme/postprocess.py", line 27, in <module>
    from bs4 import BeautifulSoup, Comment
ModuleNotFoundError: No module named 'bs4'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sitewide-development/envs/latest/lib/python3.12/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/sitewide-development/envs/latest/lib/python3.12/site-packages/sphinx/application.py", line 253, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sitewide-development/envs/latest/lib/python3.12/site-packages/sphinx/application.py", line 429, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sitewide-development/envs/latest/lib/python3.12/site-packages/sphinx/registry.py", line 451, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxawesome_theme (exception: No module named 'bs4')

Extension error:
Could not import extension sphinxawesome_theme (exception: No module named 'bs4')

**Comment by humitos** [comment]
@onyeibo why are not you installing it by doing `pip install sphinxawesome-theme` directly?

**Comment by onyeibo** [comment]
> @onyeibo why are not you installing it by doing `pip install sphinxawesome-theme` directly?

Where? You mean at **readthedocs**? How do I do that?  I installed it on the development source folder but that is for local compilation and testing.  Virtual environs don't reach `Git`.  Hence **readthedocs** must be running their own virtual environment.  How do I get **readthedocs** to install `sphinxawesome-theme`.  They dont have a problem with `alabaster` _(whereas I prefer awesome)_

**Comment by humitos** [comment]
Yes, I mean in Read the Docs. You can use `python.install` (https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install) in your YAML file and point to the `requirements.txt` file with all the dependencies you need.

You can also take a look at this guide: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

**Comment by onyeibo** [comment]
> Yes, I mean in Read the Docs. You can use `python.install` (https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install) in your YAML file and point to the `requirements.txt` file with all the dependencies you need.
> 
> You can also take a look at this guide: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

Thanks a lot!  I have learned something from this.  Your response was what I needed.  Readthedocs has just built my docs with Awesome them -- PASSED!
