### ISSUE TITLE
Build error with 1.16.0

### ISSUE THREAD

**Issue by languitar** [kai687/sphinxawesome-theme#198]
I just tried upgrading to the new release. Building ends up in this error:

```
writing output... [ 26%] howtos/setup-new-project                                   
Exception occurred:
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/html_translator.py", line 81, in depart_title
    node["ids"][0], node.astext()
IndexError: list index out of range
The full traceback has been saved in /tmp/sphinx-err-sh07_7k_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

This is the full log:

```
# Sphinx version: 3.3.0
# Python version: 3.8.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  5%] glossary
#   writing output... [ 10%] howtos/aws-access
#   writing output... [ 15%] howtos/index
#   writing output... [ 21%] howtos/infrastructure-access-from-home
#   writing output... [ 26%] howtos/setup-new-project
# Loaded extensions:
#   sphinx.ext.mathjax (3.3.0) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinxawesome.sampdirective (1.0.5) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome/sampdirective/__init__.py
#   sphinxawesome_theme.highlighting (1.16.0) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/highlighting.py
#   sphinxawesome_theme.postprocess (1.16.0) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/postprocess.py
#   sphinxawesome_theme.html_translator (1.16.0) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/html_translator.py
#   sphinxawesome_theme.admonition_ids (1.16.0) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/admonition_ids.py
#   sphinxawesome_theme.jinja_filters (1.16.0) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/jinja_filters.py
#   sphinxawesome_theme (1.16.0) from /home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/__init__.py
Traceback (most recent call last):
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_all()
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 260, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 597, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/writers/html.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinx/util/docutils.py", line 485, in dispatch_departure
    method(node)
  File "/home/languitar/src/planone-dev-handbook/.venv/lib/python3.8/site-packages/sphinxawesome_theme/html_translator.py", line 81, in depart_title
    node["ids"][0], node.astext()
IndexError: list index out of range
```

**Comment by kai687** [comment]
Aaargh. It should be `node.parent["ids"][0]`. I'm really sorry about that.

**Comment by kai687** [comment]
Although I thought I tested this. This part of the code runs when you have headings after a `..contents::` directive. Why did this not show up, I wonder.

**Comment by kai687** [comment]
Looks like it works for me because I used the `sphinx.ext.autosectionlabel` extension. I can reproduce the error, if I don't use this extension _and_ use the `..contents` directive.

**Comment by languitar** [comment]
> Looks like it works for me because I used the `sphinx.ext.autosectionlabel` extension. I can reproduce the error, if I don't use this extension _and_ use the `..contents` directive.

That could be the case i was facing as well. Is there already a new release with this version that I could try?

**Comment by kai687** [comment]
Not a new release yet, I want to write a couple of tests to make sure that I know the cases I want to cover.
In the mean time, you could install from master in your current virtual env, using:

```shell
 pip install git+https://github.com/kai687/sphinxawesome-theme.git
```

Based on the preliminary testing I did, PR #199 really addressed this particular problem but I would like to write more robust tests for this.
