### ISSUE TITLE
TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by nicrie** [kai687/sphinxawesome-theme#778]
Creating my docs with standard Sphinx theme `classic` works. However, when I switch to `sphinxawesome_theme`, it produces the following error:

```py
Traceback (most recent call last):
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/application.py", line 321, in _init_builder
    self.builder.init()
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 220, in init
    self.init_templates()
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 268, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/theming.py", line 240, in create
    self.load_extra_theme(name)
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/theming.py", line 185, in load_extra_theme
    self.load_external_theme(name)
  File "/home/nrieger/anaconda3/envs/xeofs/lib/python3.8/site-packages/sphinx/theming.py", line 207, in load_external_theme
    theme_entry_points = entry_points(group='sphinx.html_themes')
TypeError: entry_points() got an unexpected keyword argument 'group'
```

#### System information
Ubuntu 20.04
sphinxawesome-theme version: 3.3.0
Sphinx version: 4.4.0
Python version: 3.8.12 (CPython)
Docutils version: 0.17.1 release
Jinja2 version: 3.0.3

When I tried it a couple of days ago it still worked, recreating the docs today failed. But to be honest, I also made some changes in the rest of my package so it might be due to this. ;)  

Since the error message points to the external theme, though, and the default theme works, I thought I'd start here :)

PS: Awesome theme!

**Comment by kai687** [comment]
Hi @nicrie and thanks for your kind comment. Did you try using an older version of the theme? E.g. `pip install sphinxawesome-theme==3.2.3`?

If it works, then it is indeed an issue with the Awesome Theme.

An issue with the environment is also possible:

Sphinx seems to fail when it tries to import the theme. The error:

```
entry_points() got an unexpected keyword argument 'group'
```

Seems to indicate that the function `entry_points()`doesn't expect the `group` keyword.
This function is either from the `importlib.metadata` module or `importlib_metadata` (backported for older Python versions).

The only thing I can imagine right now is that somehow the `importlib` library is older in your environment, where the `entry_points()` function didn't have the `group` keyword maybe?

I'm not using anaconda, but with a Python 3.8.12 on my machine in a fresh environment, I do this minimal working example:

```
pip -m venv _env
source _env/bin/activate
pip install sphinxawesome-theme
echo 'exclude_pattern=["_env"] > conf.py
echo 'html_theme="sphinxawesome_theme"' >> conf.py
echo 'Test' > index.rst
echo '====' >> index.rst
sphinx-build . _build
```

This works for me.

Can you spot any differences?

**Comment by nicrie** [comment]
Thanks @kai687 for pointing me to `importlib.metadata`! Somehow the package was installed twice - through `pip` and `conda` - which apparently created some confusion. Cleaning up the mess helped and now your theme compiles again both on version `3.2.3` and `3.3.0` :) Thanks for your quick reply and sharing your work here!
